### ISSUE TITLE
Missing readme.md

### ISSUE THREAD

**Issue by ricardovsilva** [jhonnymoreira/obbie#4]
A readme.md file that explain what this repository is about is a good entry point to new devs. Is nearly impossible to review or give some ideas without know what repository author is purposing.

A good example of readme contains, but is not limited to:
- What is this repository;
- Wich kind of problem it solves;
- How can to use;
- How to contribute.

**Comment by jhonnymoreira** [comment]
@ricardovsilva thanks for the issue! I'll work on this later today. Would you like to review the PR?

**Comment by ricardovsilva** [comment]
@jhonnymoreira sure!

**Comment by jhonnymoreira** [comment]
I started the _readme_ with the basics, but there is a few more things remaining, such as API description and how to contribute. The API will be generated through JSDocs, probably. In the future, those annotations may be replaced with Flow or TypeScript annotations!

Again, thanks for taking part of your time to open this issue and for the patience too!

Commit: https://github.com/jhonnymoreira/obbie/commit/b96a3ffac08961081bcc0ae1e9c5853eb6ce956d
